# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:
  push:
    branches:
      - manage-store

name: Create Store

permissions: 
  contents: write

jobs:
  store:
    runs-on: ubuntu-latest
    name: Create Store
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, any::anytime, any::pandoc
          needs: check

      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.7.31

      - name: Create Store
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          Rscript scripts/make-store.R
      
      - name: Upload store db
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMIT_HASH=$(git -C ~/github/quarto-dev/quarto-web rev-parse --short HEAD)
          echo "${COMMIT_HASH}" > LATEST 
          gh release upload store "quarto.ragnar.store#quarto.ragnar.store-${COMMIT_HASH}" LATEST --clobber

